### ISSUE TITLE
Bonus features

### ISSUE THREAD

**Issue by gavinskycastle** [4201VitruvianBots/VitruvianMatchSchedule#7]
- [ ] Add debug code to test how the code would've operated at different times
- [ ] Fix issue where once a timer for a match ends, it doesn't automatically switch to the next match timer unless you manually refresh
- [ ] Fix issue where already loaded data randomly disappears when quickly switching team numbers?
- [ ] Add sliding animation for settings button
- [ ] Add search dropdown for available teams instead of number input
- [ ] Show results of already finished matches
- [ ] Highlight next match
- [ ] Show match overview/rankings similar to statbotics page (maybe even with pit photos?)

**Comment by ThePotatoArchivist** [comment]
Maybe a search dropdown
